version: '3.8'

services:
  # API Backend para desenvolvimento
  api:
    build:
      context: ./app/api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./app/api:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - farmup-network

  # Client Frontend para desenvolvimento (Vite dev server)
  client-dev:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./app/client:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - api
    networks:
      - farmup-network

networks:
  farmup-network:
    driver: bridge