version: '3.8'
services:
  api:
    build: ./api
    container_name: farmaup-api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules

  client:
    build: ./client
    container_name: farmaup-client
    ports:
      - "8080:80"
    depends_on:
      - api
