version: "3.8"

services:
  # API Backend
  api:
    build: ./app/api
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production

  # Client Frontend
  client:
    build: ./app/client
    ports:
      - "3000:80"
    depends_on:
      - api
